## Shell command execution and output capture for the get tool.
##
## :Author: WaterRun
## :GitHub: https://github.com/Water-Run/get
## :Date: 2026-04-16
## :File: exec.nim
## :License: AGPL-3.0
##
## This module provides procedures to execute shell commands
## generated by the LLM, capture their combined stdout/stderr
## output, and enforce safety constraints including forbidden-
## command-pattern regex validation and interactive manual-confirm
## gating.  Commands are run through the configured shell via
## startProcess with the bundled bin/ directory prepended to PATH
## so that shipped tools (rg, fd, sg, bat, mdcat, pmc,
## treepp/tree) are available to generated commands.
##
## The command-pattern acts as a forbidden-command filter: when a
## command matches the pattern, it is rejected.  A default pattern
## covering common destructive operations is defined in utils.nim
## and used when the user has not set a custom pattern.
##
## The regex engine is the pure-Nim ``regex`` package, eliminating
## the runtime dependency on libpcre and enabling fully static
## binaries.
##
## The manual-confirm prompt reads user input via stdin as the
## primary method, falling back to /dev/tty (Unix) or CONIN$
## (Windows) when stdin is unavailable.

{.experimental: "strictFuncs".}

import std/[envvars, os, osproc, strtabs, streams,
            strformat, strutils]

import regex

import style
import utils

# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------

## Encapsulates the result of a shell command execution.
type
  ExecResult* = object
    output*: string   ## Combined stdout and stderr output.
    exitCode*: int    ## Process exit code (0 = success).

# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

## Builds the argument list for invoking a command through the
## given shell.  PowerShell/pwsh receives ``-NoProfile
## -NonInteractive -Command <cmd>``; cmd.exe receives ``/C <cmd>``;
## everything else receives ``-c <cmd>``.
##
## :param shell: Shell executable name or path.
## :param command: The command string to execute.
## :returns: A seq of shell arguments.
func implBuildShellArgs(
  shell: string,
  command: string
): seq[string] =
  let lower = toLowerAscii(shell)
  if lower.contains("powershell") or
      lower.contains("pwsh"):
    result = @[
      "-NoProfile", "-NonInteractive",
      "-Command", command
    ]
  elif lower.contains("cmd"):
    result = @["/C", command]
  else:
    result = @["-c", command]

## Creates a StringTableRef containing the current environment with
## binDir prepended to PATH.  Returns nil when binDir is empty or
## does not exist.
##
## :param binDir: Absolute path to the bundled bin directory.
## :returns: A modified environment table, or nil.
proc implBuildEnv(binDir: string): StringTableRef =
  if binDir.len == 0 or not dirExists(binDir):
    return nil
  when defined(windows):
    var env = newStringTable(modeCaseInsensitive)
  else:
    var env = newStringTable(modeCaseSensitive)
  for key, val in envPairs():
    env[key] = val
  var curPath = ""
  if env.hasKey("PATH"):
    curPath = env["PATH"]
  when defined(windows):
    env["PATH"] = binDir & ";" & curPath
  else:
    env["PATH"] = binDir & ":" & curPath
  result = env

## Reads a single line of text from the controlling terminal.
## Tries stdin first, then falls back to /dev/tty (Unix) or
## CONIN$ (Windows).
##
## :returns: The trimmed user input, or empty on failure.
proc implReadTerminalLine(): string =
  try:
    result = stdin.readLine()
    return
  except IOError, EOFError:
    discard
  try:
    when defined(windows):
      let tty = open("CONIN$", fmRead)
    else:
      let tty = open("/dev/tty", fmRead)
    try:
      result = tty.readLine()
    finally:
      tty.close()
    return
  except IOError, EOFError, OSError:
    discard
  result = ""

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

## Checks whether a user-provided forbidden-command-pattern regex
## adequately covers common dangerous commands.  Returns a warning
## message listing uncovered commands, or an empty string.
##
## :param pattern: The user's forbidden-command regex.
## :returns: Warning text, or empty string if adequate.
##
## .. code-block:: nim
##   runnableExamples:
##     discard checkPatternSafety("^ls")
proc checkPatternSafety*(
  pattern: string
): string =
  if pattern.len == 0:
    return ""
  var uncovered: seq[string] = @[]
  for name in DANGEROUS_COMMAND_NAMES:
    try:
      if not name.contains(re2(pattern)):
        uncovered.add(name)
    except CatchableError:
      discard
  if uncovered.len > 0:
    result = "warning: custom command-pattern " &
      "does not block these dangerous commands: " &
      uncovered.join(", ")
  else:
    result = ""

## Validates a command string against a forbidden-command regex
## pattern.  Returns true when the command is allowed (no match).
##
## :param command: The command to validate.
## :param pattern: A forbidden-command regex string.
## :returns: true if the command is allowed.
## :raises: GetError: If the pattern is not a valid regex.
##
## .. code-block:: nim
##   runnableExamples:
##     assert validateCommandPattern("ls -la", "\\brm\\b")
##     assert not validateCommandPattern(
##       "rm -rf /", "\\brm\\b")
proc validateCommandPattern*(
  command: string,
  pattern: string
): bool =
  try:
    result = not command.contains(re2(pattern))
  except CatchableError:
    raise newException(GetError,
      fmt"invalid command-pattern regex: {pattern}")

## Displays the command and reads a y/N confirmation from the user.
## Returns true only when the user types "y" (case-insensitive).
##
## :param command: The command awaiting confirmation.
## :param sk: The active output style.
## :param showCommand: Whether to display the command in the prompt.
## :returns: true if the user confirms with "y".
##
## .. code-block:: nim
##   runnableExamples:
##     # Interactive — cannot be tested non-interactively.
##     discard
proc confirmExecution*(
  command: string,
  sk: StyleKind = skSimp,
  showCommand: bool = true
): bool =
  case sk
  of skSimp:
    if showCommand:
      stderr.write(
        "execute: " & command &
        "\nconfirm? (y/N): ")
    else:
      stderr.write("confirm? (y/N): ")
  of skVivid:
    if showCommand:
      stderr.write(
        ANSI_MAGENTA & "❯ " & ANSI_BOLD &
        command & ANSI_RESET &
        "\n" & ANSI_YELLOW & ANSI_BOLD &
        "confirm? (y/N): " & ANSI_RESET)
    else:
      stderr.write(
        ANSI_YELLOW & ANSI_BOLD &
        "confirm? (y/N): " & ANSI_RESET)
  stderr.flushFile()
  stdout.flushFile()
  let response = implReadTerminalLine()
  result = toLowerAscii(response.strip()) == "y"

## Executes a command string through the specified shell and
## returns the captured combined output together with the exit
## code.
##
## :param command: The command to execute.
## :param shell: Shell executable name or path.
## :param binDir: Optional bundled-binary directory to prepend
##                to PATH.
## :returns: An ExecResult with captured output and exit code.
## :raises: GetError: If the shell process cannot be started.
##
## .. code-block:: nim
##   runnableExamples:
##     # Platform-specific — illustrative only.
##     discard
proc executeCommand*(
  command: string,
  shell: string,
  binDir: string = ""
): ExecResult =
  let args = implBuildShellArgs(shell, command)
  let env = implBuildEnv(binDir)
  var p: Process
  try:
    p = startProcess(
      shell,
      args = args,
      env = env,
      options = {poStdErrToStdOut, poUsePath}
    )
  except OSError as e:
    raise newException(GetError,
      fmt"cannot start shell '{shell}': {e.msg}")
  let output = p.outputStream.readAll()
  let exitCode = p.waitForExit()
  p.close()
  result = ExecResult(
    output: output,
    exitCode: exitCode
  )