## Shell command execution and output capture for the get tool.
##
## :Author: WaterRun
## :GitHub: https://github.com/Water-Run/get
## :Date: 2026-08-24
## :File: exec.nim
## :License: AGPL-3.0
##
## This module provides procedures to execute shell commands
## generated by the LLM, capture their combined stdout/stderr
## output, and present interactive manual-confirm gating.
## Commands are run through the configured shell via
## startProcess with a sanitized child environment. Trusted system directories
## lead PATH, while inherited executable directories outside the workspace and
## temporary trees keep ordinary user-installed diagnostic tools available.
##
## When the configured shell is PowerShell, a UTF-8 prelude is
## injected before every user-supplied command so that native
## programs (such as ``treepp`` or ``ipconfig``) whose output
## flows through a pipe are not truncated or garbled by the
## default Windows code page (for example GBK/CP936 on Chinese
## installations).
##
## Forbidden-command-pattern validation lives in utils.nim so
## that the config module can reference it without a circular
## dependency.

{.experimental: "strictFuncs".}

import std/[
  envvars, locks, monotimes, os, osproc, streams, strformat, strtabs, strutils,
  times
]

when defined(windows):
  import std/atomics

when defined(posix):
  import std/posix

import style
import utils

when defined(macosx):
  import command_policy

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

## PowerShell prelude injected before every user-supplied command. It sets
## ``$OutputEncoding`` to UTF-8 and reconstructs ``PSModulePath`` from the
## running PowerShell distribution plus administrator-controlled Windows
## module directories. This prevents a removed user module path from being
## silently recreated during automatic module discovery.
##
## Two common-looking fixes are deliberately NOT applied:
##
## ``[Console]::OutputEncoding`` is left untouched.  Native Win32
## tools emit OEM-encoded bytes (GBK, Shift-JIS, etc.); overriding
## this property causes mis-decoding and pipe truncation — the root
## cause of the "``ipconfig`` shows only its English header" symptom.
##
## ``chcp 65001`` is NOT executed.  It mutates the shared console
## code page, which under PowerShell 7 disrupts child output
## buffering and produces an empty pipe.
const POWERSHELL_UTF8_PRELUDE =
  "$OutputEncoding = " &
  "[System.Text.UTF8Encoding]::new(); " &
  "$__getV3Modules = @([System.IO.Path]::Combine($PSHOME, 'Modules')); " &
  "if ([System.Environment]::OSVersion.Platform -eq " &
  "[System.PlatformID]::Win32NT) { " &
  "$__getV3System = [System.Environment]::SystemDirectory; " &
  "if ($__getV3System) { $__getV3Modules += " &
  "[System.IO.Path]::Combine($__getV3System, " &
  "'WindowsPowerShell\\v1.0\\Modules') }; " &
  "$__getV3ProgramFiles = [System.Environment]::GetFolderPath(" &
  "[System.Environment+SpecialFolder]::ProgramFiles); " &
  "if ($__getV3ProgramFiles) { " &
  "$__getV3Modules += [System.IO.Path]::Combine(" &
  "$__getV3ProgramFiles, 'WindowsPowerShell\\Modules'); " &
  "$__getV3Modules += [System.IO.Path]::Combine(" &
  "$__getV3ProgramFiles, 'PowerShell\\Modules') } }; " &
  "$env:PSModulePath = [string]::Join(" &
  "[string][System.IO.Path]::PathSeparator, [string[]]$__getV3Modules); " &
  "$env:COMPUTERNAME = " &
  "[System.Net.Dns]::GetHostName(); " &
  "Set-Alias -Name python3 -Value python " &
  "-Scope Local -ErrorAction SilentlyContinue; "

when defined(macosx):
  ## macOS Seatbelt profile used by the read-only Harness executor. Existing
  ## stdout/stderr descriptors remain usable; only new filesystem writes are
  ## denied, with the conventional null devices retained as sinks.
  const MACOS_READ_ONLY_PROFILE =
    "(version 1)" &
    "(allow default)" &
    "(deny file-write*)" &
    "(allow file-write-data (literal \"/dev/null\") " &
      "(literal \"/dev/tty\"))"

# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------

## Encapsulates the result of a shell command execution.
type
  ExecResult* = object
    output*: string    ## Combined stdout and stderr output.
    exitCode*: int     ## Process exit code (0 = success).
    elapsedMs*: int64  ## Wall-clock execution duration in milliseconds.
    timedOut*: bool    ## Whether the configured deadline stopped the process.
    truncated*: bool   ## Whether the output byte cap stopped capture.

when defined(windows):
  ## Shares deadline state with a Windows command watchdog thread.
  type
    WatchdogContext = object
      process: Process           ## Process whose tree is being supervised.
      completed: ptr Atomic[bool] ## Set when normal capture has completed.
      timedOut: ptr Atomic[bool] ## Set when the deadline is reached.
      timeoutMs: int             ## Positive deadline in milliseconds.

# ---------------------------------------------------------------------------
# Module state
# ---------------------------------------------------------------------------

## Maximum concurrently tracked command processes.
const MAX_TRACKED_PROCESSES = 1024

## Protects the active child-process registry across parallel workers.
var activeProcessLock: Lock

## Serializes process creation until new parent-side pipe handles are CLOEXEC.
var processStartLock: Lock

## Serializes and caches the once-per-process OS sandbox capability probe.
var readOnlySandboxLock: Lock

## -1 means unprobed, 0 unavailable, 1 /usr/bin runner, and 2 /bin runner.
## An integer avoids sharing a GC-managed string between Harness workers.
var readOnlySandboxState = -1

## Contains raw shell references that must be cancelled on Ctrl+C.
## Workers retain ownership; raw pointers avoid cross-thread GC roots.
var activeProcessSlots: array[MAX_TRACKED_PROCESSES, pointer]

initLock(activeProcessLock)
initLock(processStartLock)
initLock(readOnlySandboxLock)

# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

## Adds one started shell to the interrupt-cancellation registry.
##
## :param process: Started shell process.
proc implRegisterProcess(process: Process) {.gcsafe.} =
  acquire(activeProcessLock)
  for index in 0 ..< activeProcessSlots.len:
    if activeProcessSlots[index].isNil:
      activeProcessSlots[index] = cast[pointer](process)
      break
  release(activeProcessLock)

## Removes one completed shell from the interrupt-cancellation registry.
##
## :param process: Completed shell process.
proc implUnregisterProcess(process: Process) {.gcsafe.} =
  acquire(activeProcessLock)
  let target = cast[pointer](process)
  for index in 0 ..< activeProcessSlots.len:
    if activeProcessSlots[index] == target:
      activeProcessSlots[index] = nil
      break
  release(activeProcessLock)

## Prevents future child processes from inheriting parent-side process pipes.
##
## :param process: Newly started process whose pipe handles must be isolated.
proc implPreventPipeInheritance(process: Process) {.gcsafe.} =
  when declared(setInheritable):
    discard setInheritable(process.inputHandle, false)
    discard setInheritable(process.outputHandle, false)
    discard setInheritable(process.errorHandle, false)

## Stops a shell process and, on POSIX, every child in its process group.
##
## :param process: Running shell process to stop.
proc implTerminateProcessTree(process: Process) {.gcsafe.} =
  if process.isNil:
    return
  when defined(posix):
    let groupId = Pid(-process.processID)
    discard posix.kill(groupId, SIGTERM)
    # Keep the shell stoppable even if a platform's osproc implementation
    # could not establish the requested process group.
    discard posix.kill(Pid(process.processID), SIGTERM)
    sleep(50)
    # The leader may exit on TERM while a descendant ignores it. Kill the
    # group before reaping the leader, so those descendants cannot survive.
    discard posix.kill(groupId, SIGKILL)
    discard posix.kill(Pid(process.processID), SIGKILL)
  else:
    try:
      var killer: Process
      acquire(processStartLock)
      try:
        killer = startProcess(
          "taskkill",
          args = @[
            "/PID", $process.processID,
            "/T", "/F"
          ],
          options = {poUsePath, poStdErrToStdOut}
        )
        implPreventPipeInheritance(killer)
      finally:
        release(processStartLock)
      discard killer.outputStream.readAll()
      discard killer.waitForExit(2000)
      killer.close()
    except OSError, IOError, ValueError:
      try:
        process.terminate()
      except OSError, ValueError:
        discard

when defined(windows):
  ## Enforces one Windows process deadline while its blocking pipe is drained
  ## elsewhere. POSIX capture uses poll(2) and needs no watchdog thread.
  ##
  ## :param context: Process and atomic deadline state copied into the thread.
  proc implWatchCommand(context: WatchdogContext) {.thread, gcsafe.} =
    var waitedMs = 0
    while waitedMs < context.timeoutMs:
      if context.completed[].load():
        return
      let interval = min(10, context.timeoutMs - waitedMs)
      sleep(interval)
      waitedMs += interval
    if not context.completed[].load():
      context.timedOut[].store(true)
      implTerminateProcessTree(context.process)

## Copies one captured pipe chunk without exceeding the configured byte cap.
##
## :returns: true when bytes had to be discarded because the cap was reached.
proc implCaptureChunk(
  output: var string,
  data: pointer,
  count: int,
  maxOutputBytes: int
): bool =
  if count <= 0:
    return false
  if maxOutputBytes > 0 and output.len >= maxOutputBytes:
    return true
  let remaining =
    if maxOutputBytes <= 0:
      count
    else:
      min(count, maxOutputBytes - output.len)
  if remaining > 0:
    let previousLength = output.len
    output.setLen(previousLength + remaining)
    copyMem(addr output[previousLength], data, remaining)
  result = remaining < count

## Builds the argument list for invoking a command through the
## given shell.  For PowerShell and pwsh shells, the UTF-8
## prelude defined by POWERSHELL_UTF8_PRELUDE is prepended to
## the command so that native program output captured through
## a pipe is not truncated or garbled by the default Windows
## code page.
##
## :param shell: Shell executable name or path.
## :param command: The command string to execute.
## :returns: A seq of shell arguments ready for startProcess.
func implBuildShellArgs(
  shell: string,
  command: string
): seq[string] =
  let lower = toLowerAscii(shell)
  if lower.contains("powershell") or
      lower.contains("pwsh"):
    # Prepend the UTF-8 prelude so Windows non-ASCII output
    # survives the pipe transcoding layer.
    let wrapped = POWERSHELL_UTF8_PRELUDE & command
    result = @[
      "-NoProfile", "-NonInteractive",
      "-Command", wrapped]
  elif lower.contains("cmd"):
    # /D disables per-user and machine AutoRun command injection.
    # /V:OFF makes delayed !VAR! expansion deterministic and unavailable.
    result = @["/D", "/Q", "/V:OFF", "/C", command]
  elif lower.contains("fish"):
    result = @["--no-config", "-c", command]
  elif lower.contains("zsh"):
    result = @["-f", "-c", command]
  elif lower.contains("bash"):
    result = @["--noprofile", "--norc", "-c", command]
  else:
    result = @["-c", command]

proc implNormalizedExecutableDirectory(path: string): string =
  if path.len == 0 or not path.isAbsolute:
    return ""
  try:
    result = normalizedPath(path)
  except OSError, ValueError:
    return ""

func implComparablePath(path: string): string =
  when defined(windows):
    result = toLowerAscii(path)
  else:
    result = path

func implPathIsInside(path: string, root: string): bool =
  if path.len == 0 or root.len == 0:
    return false
  result = path == root or path.startsWith(root & $DirSep)

proc implAppendExecutableDirectory(
  entries: var seq[string],
  comparableEntries: var seq[string],
  candidate: string,
  current: string,
  temporary: string,
  inherited: bool
) =
  let normalized = implNormalizedExecutableDirectory(candidate)
  let comparable = implComparablePath(normalized)
  if comparable.len == 0 or comparable in comparableEntries:
    return
  if inherited and (
      implPathIsInside(comparable, current) or
      implPathIsInside(comparable, temporary)):
    return
  when defined(posix):
    if inherited and (
        implPathIsInside(comparable, "/tmp") or
        implPathIsInside(comparable, "/var/tmp") or
        implPathIsInside(comparable, "/dev/shm")):
      return
  entries.add(normalized)
  comparableEntries.add(comparable)

proc implSanitizedExecutablePath(rawPath: string): string =
  ## Keeps user-installed tools available while preventing a repository or
  ## temporary directory from shadowing an allowlisted system executable.
  ## Administrator-controlled platform directories are deliberately first.
  var entries: seq[string] = @[]
  var comparableEntries: seq[string] = @[]
  let current = implComparablePath(
    implNormalizedExecutableDirectory(getCurrentDir()))
  let temporary = implComparablePath(
    implNormalizedExecutableDirectory(getTempDir()))

  template add(candidate: string, inherited: bool) =
    implAppendExecutableDirectory(
      entries, comparableEntries, candidate, current, temporary, inherited)

  when defined(windows):
    let windowsRoot = getEnv("SystemRoot", r"C:\Windows")
    add(windowsRoot / "System32", false)
    add(windowsRoot, false)
    add(windowsRoot / "System32" / "WindowsPowerShell" / "v1.0", false)
    let programFiles = getEnv("ProgramFiles", r"C:\Program Files")
    add(programFiles / "PowerShell" / "7", false)
  else:
    for trusted in [
      "/usr/bin", "/bin", "/usr/sbin", "/sbin", "/usr/local/bin",
      "/opt/homebrew/bin", "/opt/local/bin", "/home/linuxbrew/.linuxbrew/bin"
    ]:
      add(trusted, false)

  for entry in rawPath.split(PathSep):
    add(entry, true)
  result = entries.join($PathSep)

## Builds a child environment without executable startup hooks.
##
## The command policy treats the parent environment as untrusted input: shell
## startup hooks, exported Bash functions, dynamic-loader injection, language
## startup options, Git helper injection, and TLS key-log output are removed.
## Pagers are forced into non-interactive stdout mode and Git optional locks are
## disabled so read commands do not refresh repository metadata.
proc implSanitizedEnvironment(): StringTableRef =
  result = newStringTable(
    when defined(windows): modeCaseInsensitive
    else: modeCaseSensitive)
  for key, value in envPairs():
    let upper = toUpperAscii(key)
    let blocked = upper in [
      "BASH_ENV", "ENV", "ZDOTDIR", "PROMPT_COMMAND", "CDPATH", "IFS",
      "SHELLOPTS", "BASHOPTS", "PS4", "BASH_XTRACEFD", "GCONV_PATH",
      "GLIBC_TUNABLES", "LOCPATH", "GIO_EXTRA_MODULES", "GIO_MODULE_DIR",
      "GTK_PATH", "GTK_MODULES", "QT_PLUGIN_PATH",
      "QT_QPA_PLATFORM_PLUGIN_PATH", "QML2_IMPORT_PATH", "GI_TYPELIB_PATH",
      "OCL_ICD_VENDORS", "LIBGL_DRIVERS_PATH", "VK_ICD_FILENAMES",
      "VK_DRIVER_FILES", "CUDA_INJECTION32_PATH", "CUDA_INJECTION64_PATH",
      "PYTHONSTARTUP", "PYTHONINSPECT", "PYTHONPATH", "PYTHONHOME",
      "PYTHONWARNINGS", "NODE_OPTIONS", "NODE_PATH", "RUBYOPT", "RUBYLIB",
      "PERL5OPT", "PERL5LIB", "PERLLIB", "PHPRC", "PHP_INI_SCAN_DIR",
      "LUA_INIT", "LUA_PATH", "LUA_CPATH", "JULIA_PROJECT",
      "JULIA_LOAD_PATH", "JULIA_DEPOT_PATH",
      "JAVA_TOOL_OPTIONS", "JDK_JAVA_OPTIONS", "_JAVA_OPTIONS",
      "GOENV", "GOTOOLCHAIN", "GOFLAGS", "GOWORK", "GOMODCACHE",
      "GOCACHE", "GOPATH", "GOROOT", "GOPROXY", "GONOSUMDB",
      "GONOPROXY", "GOPRIVATE", "GOSUMDB", "GOINSECURE",
      "DOTNET_STARTUP_HOOKS", "DOTNET_ADDITIONAL_DEPS",
      "DOTNET_SHARED_STORE", "COREHOST_TRACEFILE", "OPENSSL_CONF",
      "OPENSSL_ENGINES", "OPENSSL_MODULES", "MAKEFLAGS", "MFLAGS",
      "MAKEFILES", "PSMODULEPATH", "KUBECONFIG", "KUBECACHEDIR",
      "KUBE_EDITOR", "KUBE_EXTERNAL_DIFF", "KUBERNETES_EXEC_INFO",
      "APT_CONFIG", "PIP_CONFIG_FILE", "CARGO_HOME", "RUSTUP_HOME",
      "NIM_CONFIG_DIR", "NIMBLE_DIR", "NIMBLE_PATH",
      "FISH_FUNCTION_PATH", "FISH_COMPLETE_PATH", "FISH_USER_PATHS",
      "DOCKER_CONFIG", "DOCKER_CONTEXT", "DOCKER_CLI_PLUGIN_EXTRA_DIRS",
      "PODMAN_COMPOSE_PROVIDER", "CONTAINERS_CONF",
      "CONTAINERS_STORAGE_CONF", "REGISTRY_AUTH_FILE",
      "NPM_CONFIG_USERCONFIG", "YARN_RC_FILENAME", "YARN_IGNORE_PATH",
      "RUSTC_WRAPPER", "RUSTC_WORKSPACE_WRAPPER", "RIPGREP_CONFIG_PATH",
      "TAR_OPTIONS", "TAR_RSH", "TAPE", "RSH", "GZIP", "BZIP2", "XZ_OPT",
      "XZ_DEFAULTS", "UNZIP", "UNZIPOPT", "ZIPINFO", "ZIPINFOOPT",
      "WGETRC", "CURL_HOME", "LESSOPEN", "LESSCLOSE", "MANOPT",
      "SYSTEMD_EDITOR", "SYSTEMD_SSH", "SSLKEYLOGFILE", "MALLOC_TRACE",
      "RANDFILE", "RUSTUP_TOOLCHAIN",
      "PS_PERSONALITY", "CMD_ENV", "DEVELOPER_DIR", "TOOLCHAINS",
      "SDKROOT", "XCODE_XCCONFIG_FILE", "SWIFT_EXEC",
      "SWIFT_DRIVER_SWIFT_FRONTEND_EXEC", "SWIFT_DRIVER_SWIFT_SCAN_EXEC",
      "SWIFT_DRIVER_CLANG_EXEC", "SWIFT_DRIVER_LD_EXEC",
      "LLVM_PROFILE_FILE", "GCOV_PREFIX", "GCOV_PREFIX_STRIP",
      "ASAN_OPTIONS", "LSAN_OPTIONS", "MSAN_OPTIONS", "TSAN_OPTIONS",
      "UBSAN_OPTIONS"
    ] or upper.startsWith("BASH_FUNC_") or upper.startsWith("LUA_INIT_") or
      upper.startsWith("SYSTEMD_") or upper.startsWith("GIT_") or
      upper.startsWith("LD_") or upper.startsWith("DYLD_") or
      upper.startsWith("CORECLR_") or upper.startsWith("COR_") or
      upper.startsWith("COMPLUS_") or upper.startsWith("DOTNET_") or
      upper.startsWith("NUGET_") or upper.startsWith("NPM_CONFIG_") or
      upper.startsWith("PNPM_CONFIG_") or upper.startsWith("YARN_") or
      upper.startsWith("PIP_") or upper.startsWith("CARGO_") or
      upper.startsWith("RUSTUP_") or upper.startsWith("NIMBLE_") or
      upper.startsWith("HOMEBREW_")
    if not blocked:
      if upper == "PATH":
        result[key] = implSanitizedExecutablePath(value)
      else:
        result[key] = value
  if not result.hasKey("PATH"):
    result["PATH"] = implSanitizedExecutablePath("")
  when defined(posix):
    let absoluteHome = implNormalizedExecutableDirectory(
      result.getOrDefault("HOME", ""))
    result["HOME"] = if absoluteHome.len > 0: absoluteHome else: "/"
    result["PWD"] = implNormalizedExecutableDirectory(getCurrentDir())
  result["PAGER"] = "cat"
  result["GIT_PAGER"] = "cat"
  result["MANPAGER"] = "cat"
  result["SYSTEMD_PAGER"] = "cat"
  result["LESS"] = "-FRX"
  result["LESSSECURE"] = "1"
  result["SYSTEMD_PAGERSECURE"] = "1"
  result["NoDefaultCurrentDirectoryInExePath"] = "1"
  result["GIT_OPTIONAL_LOCKS"] = "0"
  result["GIT_NO_LAZY_FETCH"] = "1"
  result["GIT_TERMINAL_PROMPT"] = "0"
  result["GIT_CONFIG_COUNT"] = "3"
  result["GIT_CONFIG_KEY_0"] = "core.fsmonitor"
  result["GIT_CONFIG_VALUE_0"] = "false"
  result["GIT_CONFIG_KEY_1"] = "diff.external"
  result["GIT_CONFIG_VALUE_1"] = ""
  result["GIT_CONFIG_KEY_2"] = "log.showSignature"
  result["GIT_CONFIG_VALUE_2"] = "false"
  result["PIP_DISABLE_PIP_VERSION_CHECK"] = "1"
  result["PIP_NO_INPUT"] = "1"
  result["NPM_CONFIG_IGNORE_SCRIPTS"] = "true"
  result["NPM_CONFIG_UPDATE_NOTIFIER"] = "false"
  result["NPM_CONFIG_AUDIT"] = "false"
  result["NPM_CONFIG_FUND"] = "false"
  result["YARN_ENABLE_SCRIPTS"] = "false"
  result["PNPM_CONFIG_IGNORE_SCRIPTS"] = "true"
  result["DOTNET_SKIP_FIRST_TIME_EXPERIENCE"] = "1"
  result["DOTNET_CLI_TELEMETRY_OPTOUT"] = "1"
  result["DOTNET_NOLOGO"] = "1"
  result["RUSTUP_AUTO_INSTALL"] = "0"
  result["RUSTUP_NO_UPDATE_CHECK"] = "1"
  result["GOENV"] = "off"
  result["GOTOOLCHAIN"] = "local"
  result["HOMEBREW_NO_AUTO_UPDATE"] = "1"
  result["HOMEBREW_NO_ANALYTICS"] = "1"

proc implResolveShellExecutable(shell: string): string =
  ## Resolve the shell through the same sanitized PATH passed to children.
  ## This closes a pre-execution shadowing gap for fake shells placed beside
  ## an untrusted project or in a temporary directory.
  if shell.contains('/') or shell.contains('\\'):
    return shell
  let sanitizedPath = implSanitizedEnvironment().getOrDefault("PATH", "")
  when defined(windows):
    let extensions =
      if shell.toLowerAscii().endsWith(".exe"): @[""]
      else: @[".exe", ".cmd", ".bat", ""]
  else:
    let extensions = @[""]
  for directory in sanitizedPath.split(PathSep):
    if directory.len == 0:
      continue
    for extension in extensions:
      let candidate = directory / (shell & extension)
      if fileExists(candidate):
        return candidate
  raise newException(GetError,
    "configured shell could not be resolved in the sanitized executable path")

when defined(linux):
  ## Start with a private minimal /dev, then expose only accelerator device
  ## families needed by observational GPU diagnostics. Block devices and the
  ## rest of host /dev stay hidden. ``--dev-bind-try`` is deliberate: query
  ## tools commonly need O_RDWR device handles even when their operation is
  ## semantically read-only, while the mandatory command policy rejects every
  ## known setter/reset/monitor form before this layer is reached.
  proc implLinuxReadOnlyDeviceArgs(): seq[string] =
    result = @[
      "--dev", "/dev",
      "--dev-bind-try", "/dev/dri", "/dev/dri",
      "--dev-bind-try", "/dev/kfd", "/dev/kfd",
      "--dev-bind-try", "/dev/dxg", "/dev/dxg",
      "--dev-bind-try", "/dev/nvidia-caps", "/dev/nvidia-caps",
      "--dev-bind-try", "/dev/nvidiactl", "/dev/nvidiactl",
      "--dev-bind-try", "/dev/nvidia-modeset", "/dev/nvidia-modeset",
      "--dev-bind-try", "/dev/nvidia-uvm", "/dev/nvidia-uvm",
      "--dev-bind-try", "/dev/nvidia-uvm-tools", "/dev/nvidia-uvm-tools"
    ]
    for deviceIndex in 0 .. 31:
      let path = "/dev/nvidia" & $deviceIndex
      result.add(@["--dev-bind-try", path, path])

## Checks one OS sandbox runner without involving the configured shell.
## Failure is silent because the semantic command policy remains mandatory and
## is the portable enforcement layer on hosts without a usable native runner.
proc implProbeSandboxRunner(
  executable: string,
  args: seq[string]
): bool {.gcsafe.} =
  var probe: Process
  try:
    acquire(processStartLock)
    try:
      probe = startProcess(
        executable,
        args = args,
        env = implSanitizedEnvironment(),
        options = {poStdErrToStdOut}
      )
      implPreventPipeInheritance(probe)
    finally:
      release(processStartLock)
    let exitCode = probe.waitForExit(2_000)
    if exitCode < 0:
      try:
        probe.terminate()
      except OSError, ValueError:
        discard
      discard probe.waitForExit(1_000)
    discard probe.outputStream.readAll()
    result = exitCode == 0
  except OSError, IOError, ValueError:
    result = false
  finally:
    if not probe.isNil:
      try:
        probe.close()
      except OSError, IOError:
        discard

## Returns a usable platform read-only runner, probing only on first use.
proc implReadOnlySandboxExecutable(): string {.gcsafe.} =
  acquire(readOnlySandboxLock)
  try:
    if readOnlySandboxState < 0:
      readOnlySandboxState = 0
      when defined(linux):
        let trueExecutable =
          if fileExists("/bin/true"): "/bin/true"
          else: "/usr/bin/true"
        var candidateIndex = 0
        for candidate in ["/usr/bin/bwrap", "/bin/bwrap"]:
          candidateIndex += 1
          if fileExists(candidate) and implProbeSandboxRunner(candidate, @[
            "--die-with-parent",
            "--ro-bind", "/", "/",
          ] & implLinuxReadOnlyDeviceArgs() & @[
            "--", trueExecutable
          ]):
            readOnlySandboxState = candidateIndex
            break
      elif defined(macosx):
        if fileExists("/usr/bin/sandbox-exec") and
            implProbeSandboxRunner("/usr/bin/sandbox-exec", @[
              "-p", MACOS_READ_ONLY_PROFILE, "/usr/bin/true"
            ]):
          readOnlySandboxState = 1
    when defined(linux):
      case readOnlySandboxState
      of 1: result = "/usr/bin/bwrap"
      of 2: result = "/bin/bwrap"
      else: result = ""
    elif defined(macosx):
      if readOnlySandboxState == 1:
        result = "/usr/bin/sandbox-exec"
    else:
      result = ""
  finally:
    release(readOnlySandboxLock)

when defined(getTest):
  ## Exposes shell startup hardening to native cross-platform tests.
  func shellArgsForTest*(shell: string, command: string): seq[string] =
    result = implBuildShellArgs(shell, command)

  ## Returns one value from the environment passed to command children.
  proc childEnvironmentValueForTest*(name: string): string =
    result = implSanitizedEnvironment().getOrDefault(name, "")

  ## Reports whether the current host has a usable native read-only runner.
  proc readOnlySandboxAvailableForTest*(): bool =
    result = implReadOnlySandboxExecutable().len > 0

## Applies small Windows-specific command compatibility rewrites
## before execution.
##
## Current rewrites:
## - In PowerShell, bare `hostname` is rewritten to
##   `[System.Net.Dns]::GetHostName()` so hostname casing matches
##   the canonical DNS host name on Windows (instead of the
##   often uppercased `hostname.exe` output).
## - If `python3` is not available but `python` is, a leading
##   `python3` token is rewritten to `python`.
##
## :param command: Raw command from the caller.
## :param shell: Shell executable name or path.
## :returns: Rewritten command, or the original command.
proc implApplyWindowsCompatCommand(
  command: string,
  shell: string
): string =
  when defined(windows):
    let trimmed = command.strip()
    if trimmed.len == 0:
      return command

    let lowerShell = toLowerAscii(shell)
    let lowerCmd = toLowerAscii(trimmed)

    if (lowerShell.contains("powershell") or
        lowerShell.contains("pwsh")) and
        lowerCmd == "hostname":
      return "[System.Net.Dns]::GetHostName()"

    var i = 0
    while i < trimmed.len and
        (trimmed[i] == ' ' or trimmed[i] == '\t'):
      i += 1
    let t1Start = i
    while i < trimmed.len and
        trimmed[i] notin {' ', '\t'}:
      i += 1
    let t1End = i
    while i < trimmed.len and
        (trimmed[i] == ' ' or trimmed[i] == '\t'):
      i += 1
    let afterTok1Start = i
    let t2Start = i
    while i < trimmed.len and
        trimmed[i] notin {' ', '\t'}:
      i += 1
    let t2End = i
    while i < trimmed.len and
        (trimmed[i] == ' ' or trimmed[i] == '\t'):
      i += 1
    let restStart = i

    let tok1 = if t1End > t1Start:
      toLowerAscii(trimmed[t1Start ..< t1End])
      else: ""
    let tok2 = if t2End > t2Start:
      toLowerAscii(trimmed[t2Start ..< t2End])
      else: ""

    if findExe("python").len > 0:
      if tok1 == "python3":
        if afterTok1Start >= trimmed.len:
          return "python"
        return "python " &
          trimmed[afterTok1Start .. ^1]
      if tok1 == "py" and tok2.startsWith("-3"):
        if restStart >= trimmed.len:
          return "python"
        return "python " & trimmed[restStart .. ^1]

    return command
  else:
    return command

## Reads a single line from the controlling terminal.  Tries
## stdin first, then falls back to /dev/tty (Unix) or CONIN$
## (Windows).
##
## :returns: The trimmed user input, or empty on failure.
proc implReadTerminalLine(): string =
  try:
    result = stdin.readLine()
    return
  except IOError, EOFError:
    discard
  try:
    when defined(windows):
      let tty = open("CONIN$", fmRead)
    else:
      let tty = open("/dev/tty", fmRead)
    try:
      result = tty.readLine()
    finally:
      tty.close()
    return
  except IOError, EOFError, OSError:
    discard
  result = ""

# ---------------------------------------------------------------------------
# Private helpers — Windows output decoding
# ---------------------------------------------------------------------------

when defined(windows):
  ## Windows ANSI (system default) code page identifier.
  const CP_ACP = 0'u32

  ## Windows OEM code page identifier (console default,
  ## e.g. CP936 on Simplified Chinese installations).
  const CP_OEMCP = 1'u32

  ## UTF-8 code page identifier.
  const CP_UTF8 = 65001'u32

  ## Minimum byte count before the UTF-16LE heuristic is
  ## allowed to accept a buffer.  Short buffers are ambiguous
  ## (e.g. a 2-byte pure-ASCII reply looks like UTF-16LE with
  ## a zero high byte), so we require a little more evidence.
  const UTF16_HEURISTIC_MIN_LEN = 8

  ## Ratio of zero high bytes required for UTF-16LE detection,
  ## expressed as a percentage of sampled 16-bit code units.
  const UTF16_HEURISTIC_MIN_RATIO = 40

  ## Upper bound on the number of 16-bit units sampled when
  ## running the UTF-16LE heuristic.
  const UTF16_HEURISTIC_SAMPLE_CAP = 512

  ## Converts a byte sequence in the given code page to a
  ## UTF-16 buffer.
  proc multiByteToWideChar(
    codePage: uint32,
    dwFlags: uint32,
    lpMultiByteStr: cstring,
    cbMultiByte: int32,
    lpWideCharStr: ptr uint16,
    cchWideChar: int32
  ): int32 {.importc: "MultiByteToWideChar",
    stdcall, dynlib: "kernel32".}

  ## Converts a UTF-16 buffer to a byte sequence in the given
  ## code page.
  proc wideCharToMultiByte(
    codePage: uint32,
    dwFlags: uint32,
    lpWideCharStr: ptr uint16,
    cchWideChar: int32,
    lpMultiByteStr: cstring,
    cbMultiByte: int32,
    lpDefaultChar: pointer,
    lpUsedDefaultChar: pointer
  ): int32 {.importc: "WideCharToMultiByte",
    stdcall, dynlib: "kernel32".}

when defined(windows):

  ## Tests whether the data begins with a UTF-8 BOM
  ## (``EF BB BF``).
  ##
  ## :param data: Raw byte string captured from a child
  ##              process.
  ## :returns: true when the first three bytes match the
  ##           UTF-8 BOM signature.
  func implHasUtf8Bom(data: string): bool =
    result = data.len >= 3 and
      byte(data[0]) == 0xEF'u8 and
      byte(data[1]) == 0xBB'u8 and
      byte(data[2]) == 0xBF'u8

  ## Tests whether the data begins with a UTF-16LE BOM
  ## (``FF FE``).
  ##
  ## :param data: Raw byte string captured from a child
  ##              process.
  ## :returns: true on UTF-16LE BOM match.
  func implHasUtf16LeBom(data: string): bool =
    result = data.len >= 2 and
      byte(data[0]) == 0xFF'u8 and
      byte(data[1]) == 0xFE'u8

  ## Tests whether the data begins with a UTF-16BE BOM
  ## (``FE FF``).
  ##
  ## :param data: Raw byte string captured from a child
  ##              process.
  ## :returns: true on UTF-16BE BOM match.
  func implHasUtf16BeBom(data: string): bool =
    result = data.len >= 2 and
      byte(data[0]) == 0xFE'u8 and
      byte(data[1]) == 0xFF'u8

  ## Performs strict validation of a byte string as UTF-8.
  ## Rejects overlong encodings, surrogate halves, and
  ## out-of-range lead bytes, so that random OEM / GBK byte
  ## streams are not mistaken for UTF-8.
  ##
  ## :param data: Raw byte string.
  ## :returns: true only when every byte participates in a
  ##           well-formed UTF-8 sequence.
  func implIsValidUtf8(data: string): bool =
    var i = 0
    while i < data.len:
      let b = byte(data[i])
      if b < 0x80'u8:
        i += 1
      elif (b and 0xE0'u8) == 0xC0'u8:
        if b < 0xC2'u8: return false
        if i + 1 >= data.len: return false
        if (byte(data[i + 1]) and 0xC0'u8) !=
            0x80'u8:
          return false
        i += 2
      elif (b and 0xF0'u8) == 0xE0'u8:
        if i + 2 >= data.len: return false
        let b1 = byte(data[i + 1])
        let b2 = byte(data[i + 2])
        if (b1 and 0xC0'u8) != 0x80'u8:
          return false
        if (b2 and 0xC0'u8) != 0x80'u8:
          return false
        if b == 0xE0'u8 and b1 < 0xA0'u8:
          return false
        if b == 0xED'u8 and b1 >= 0xA0'u8:
          return false
        i += 3
      elif (b and 0xF8'u8) == 0xF0'u8:
        if b >= 0xF5'u8: return false
        if i + 3 >= data.len: return false
        let b1 = byte(data[i + 1])
        let b2 = byte(data[i + 2])
        let b3 = byte(data[i + 3])
        if (b1 and 0xC0'u8) != 0x80'u8:
          return false
        if (b2 and 0xC0'u8) != 0x80'u8:
          return false
        if (b3 and 0xC0'u8) != 0x80'u8:
          return false
        if b == 0xF0'u8 and b1 < 0x90'u8:
          return false
        if b == 0xF4'u8 and b1 > 0x8F'u8:
          return false
        i += 4
      else:
        return false
    result = true

  ## Heuristic detector for unmarked UTF-16LE output.  On a
  ## Latin/ASCII-heavy stream every second byte is zero; we
  ## accept the buffer as UTF-16LE when the zero-high-byte
  ## ratio exceeds ``UTF16_HEURISTIC_MIN_RATIO`` percent.
  ##
  ## :param data: Raw byte string.
  ## :returns: true when the heuristic suggests UTF-16LE.
  func implLooksLikeUtf16Le(data: string): bool =
    if data.len < UTF16_HEURISTIC_MIN_LEN:
      return false
    if (data.len mod 2) != 0:
      return false
    var zeros = 0
    var samples = 0
    var i = 1
    while i < data.len and
        samples < UTF16_HEURISTIC_SAMPLE_CAP:
      if byte(data[i]) == 0'u8:
        zeros += 1
      samples += 1
      i += 2
    if samples == 0:
      return false
    result = (zeros * 100 div samples) >=
      UTF16_HEURISTIC_MIN_RATIO

when defined(windows):

  ## Decodes a UTF-16LE byte buffer into UTF-8 using the
  ## Win32 conversion routines.  Returns an empty string on
  ## conversion failure so that callers can try the next
  ## strategy.
  ##
  ## :param data: Raw UTF-16LE byte buffer (no BOM).
  ## :returns: The decoded UTF-8 string, or empty on failure.
  proc implDecodeUtf16Le(data: string): string =
    if data.len < 2:
      return ""
    let numWords = (data.len div 2).int32
    if numWords <= 0:
      return ""
    let src = cast[ptr uint16](unsafeAddr data[0])
    let utf8Len = wideCharToMultiByte(
      CP_UTF8, 0'u32, src, numWords,
      nil, 0'i32, nil, nil)
    if utf8Len <= 0:
      return ""
    result = newString(utf8Len)
    let written = wideCharToMultiByte(
      CP_UTF8, 0'u32, src, numWords,
      cstring(result), utf8Len, nil, nil)
    if written <= 0:
      return ""

  ## Decodes a UTF-16BE byte buffer into UTF-8 by first
  ## byte-swapping the input into UTF-16LE.
  ##
  ## :param data: Raw UTF-16BE byte buffer (no BOM).
  ## :returns: The decoded UTF-8 string, or empty on failure.
  proc implDecodeUtf16Be(data: string): string =
    if data.len < 2:
      return ""
    let paired = data.len - (data.len mod 2)
    if paired <= 0:
      return ""
    var swapped = newString(paired)
    var i = 0
    while i + 1 < paired:
      swapped[i] = data[i + 1]
      swapped[i + 1] = data[i]
      i += 2
    result = implDecodeUtf16Le(swapped)

  ## Decodes a byte buffer interpreted under the given
  ## Windows code page into UTF-8.  Used as the OEM/ACP
  ## fallback when no Unicode signature is present.
  ##
  ## :param data: Raw byte buffer.
  ## :param codePage: Windows code page identifier
  ##                  (e.g. ``CP_OEMCP`` or ``CP_ACP``).
  ## :returns: The decoded UTF-8 string, or empty on failure.
  proc implDecodeWithCodePage(
    data: string,
    codePage: uint32
  ): string =
    if data.len == 0:
      return ""
    let wideLen = multiByteToWideChar(
      codePage, 0'u32,
      cstring(data), data.len.int32,
      nil, 0'i32)
    if wideLen <= 0:
      return ""
    var wide = newSeq[uint16](wideLen)
    let wRet = multiByteToWideChar(
      codePage, 0'u32,
      cstring(data), data.len.int32,
      addr wide[0], wideLen)
    if wRet <= 0:
      return ""
    let utf8Len = wideCharToMultiByte(
      CP_UTF8, 0'u32, addr wide[0], wRet,
      nil, 0'i32, nil, nil)
    if utf8Len <= 0:
      return ""
    result = newString(utf8Len)
    let written = wideCharToMultiByte(
      CP_UTF8, 0'u32, addr wide[0], wRet,
      cstring(result), utf8Len, nil, nil)
    if written <= 0:
      return ""

when defined(windows):

  ## Normalises the raw byte stream captured from a Windows
  ## child process into UTF-8 using a layered strategy:
  ##
  ## 1. Recognise UTF-8 / UTF-16LE / UTF-16BE BOMs and strip
  ##    them.
  ## 2. Accept the buffer as-is when it is strictly valid
  ##    UTF-8.
  ## 3. Try the UTF-16LE heuristic for unmarked wide output
  ##    (common for programs using ``Write-Output`` in PS 7
  ##    without the prelude taking effect).
  ## 4. Fall back to the OEM console code page (e.g. CP936)
  ##    which is the default encoding of native Win32 tools
  ##    such as ``ipconfig``.
  ## 5. Fall back to the ANSI / system code page.
  ## 6. As a last resort, replace non-ASCII bytes with
  ##    ``?`` so that the caller never receives an empty
  ##    string and never has to handle decoding errors.
  ##
  ## :param data: Raw bytes from the child process pipe.
  ## :returns: A valid UTF-8 string.  Never raises.
  proc implNormalizeWindowsOutput(
    data: string
  ): string =
    if data.len == 0:
      return ""
    # 1. BOM-driven decoding.
    if implHasUtf8Bom(data):
      return data[3 .. ^1]
    if implHasUtf16LeBom(data):
      let decoded = implDecodeUtf16Le(
        data[2 .. ^1])
      if decoded.len > 0:
        return decoded
    if implHasUtf16BeBom(data):
      let decoded = implDecodeUtf16Be(
        data[2 .. ^1])
      if decoded.len > 0:
        return decoded
    # 2. Strict UTF-8 acceptance.
    if implIsValidUtf8(data):
      return data
    # 3. Unmarked UTF-16LE heuristic.
    if implLooksLikeUtf16Le(data):
      let decoded = implDecodeUtf16Le(data)
      if decoded.len > 0 and
          implIsValidUtf8(decoded):
        return decoded
    # 4. OEM code page (CP936 / CP932 / etc.).
    let oemDecoded = implDecodeWithCodePage(
      data, CP_OEMCP)
    if oemDecoded.len > 0 and
        implIsValidUtf8(oemDecoded):
      return oemDecoded
    # 5. ANSI code page.
    let acpDecoded = implDecodeWithCodePage(
      data, CP_ACP)
    if acpDecoded.len > 0 and
        implIsValidUtf8(acpDecoded):
      return acpDecoded
    # 6. Last-resort ASCII-safe replacement.  Guarantees
    # the caller receives a non-empty, valid UTF-8 string.
    result = newStringOfCap(data.len)
    for c in data:
      if byte(c) < 0x80'u8:
        result.add(c)
      else:
        result.add('?')


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

## Stops every command currently owned by this process.
##
## The Ctrl+C handler calls this before exiting so detached POSIX process
## groups and Windows child trees do not survive their parent CLI process.
##
## .. code-block:: nim
##   runnableExamples:
##     discard
proc terminateActiveCommands*() =
  acquire(activeProcessLock)
  for index in 0 ..< activeProcessSlots.len:
    let processPointer = activeProcessSlots[index]
    if not processPointer.isNil:
      implTerminateProcessTree(
        cast[Process](processPointer))
    activeProcessSlots[index] = nil
  release(activeProcessLock)

## Displays the command and reads a y/N confirmation.  Returns
## true only when the user types "y" (case-insensitive).
##
## :param command: The command awaiting confirmation.
## :param sk: The active output style.
## :param showCommand: Whether to display the command.
## :returns: true if the user confirms with "y".
##
## .. code-block:: nim
##   runnableExamples:
##     discard
proc confirmExecution*(
  command: string,
  sk: StyleKind = skSimp,
  showCommand: bool = true
): bool =
  case sk
  of skSimp:
    if showCommand:
      stderr.write(
        "execute: " & command &
        "\nconfirm? (y/N): ")
    else:
      stderr.write("confirm? (y/N): ")
  of skVivid:
    if showCommand:
      stderr.write(
        ANSI_MAGENTA &
        "\xe2\x9d\xaf " & ANSI_BOLD &
        command & ANSI_RESET &
        "\n" & ANSI_YELLOW & ANSI_BOLD &
        "confirm? (y/N): " & ANSI_RESET)
    else:
      stderr.write(
        ANSI_YELLOW & ANSI_BOLD &
        "confirm? (y/N): " & ANSI_RESET)
  stderr.flushFile()
  stdout.flushFile()
  let response = implReadTerminalLine()
  result = toLowerAscii(response.strip()) == "y"

## Executes a shell command with deadline and output-size enforcement.
##
## POSIX uses poll(2), keeping deadlines in the capture loop without a helper
## thread. Windows uses a watchdog because its portable process stream is
## blocking. POSIX shells are placed in a separate process group; Windows uses
## ``taskkill /T`` to stop the corresponding process tree. Captured Windows
## bytes retain the existing UTF normalization behavior.
##
## :param command: Validated command to execute.
## :param shell: Shell executable name or path.
## :param timeoutSec: Deadline in seconds; zero disables it.
## :param maxOutputBytes: Capture cap in bytes; zero disables it.
## :param readOnlySandbox: Add a native filesystem read-only layer when the
##   current Linux or macOS host supports one. The semantic policy remains the
##   portable authority, including on Windows and unsupported hosts.
## :returns: A bounded result with status and timing metadata.
## :raises: GetError: If the shell process cannot be started.
##
## .. code-block:: nim
##   runnableExamples:
##     discard
proc executeCommandBounded*(
  command: string,
  shell: string,
  timeoutSec: int,
  maxOutputBytes: int,
  readOnlySandbox: bool = false
): ExecResult =
  if timeoutSec < 0:
    raise newException(GetError,
      "command timeout must not be negative")
  if maxOutputBytes < 0:
    raise newException(GetError,
      "command output limit must not be negative")
  let started = getMonoTime()
  let effectiveCommand = implApplyWindowsCompatCommand(
    command, shell)
  let shellExecutable = implResolveShellExecutable(shell)
  var executable = shellExecutable
  var args = implBuildShellArgs(
    shell, effectiveCommand)
  if readOnlySandbox:
    when defined(linux):
      let bubblewrap = implReadOnlySandboxExecutable()
      if bubblewrap.len > 0:
        executable = bubblewrap
        args = @[
          "--die-with-parent",
          "--ro-bind", "/", "/",
        ] & implLinuxReadOnlyDeviceArgs() & @[
          "--chdir", getCurrentDir(),
          "--", shellExecutable
        ] & args
    elif defined(macosx):
      # sandbox-exec cannot launch Apple's set-id diagnostic readers (ps, top,
      # traceroute), and it silently empties ``launchctl list``. Only a command
      # that has already passed the full mandatory policy may take this narrow
      # compatibility path; all other macOS commands keep Seatbelt's
      # filesystem-write denial.
      if not macosRequiresUnsandboxedReader(command, shell):
        let sandboxExec = implReadOnlySandboxExecutable()
        if sandboxExec.len > 0:
          executable = sandboxExec
          args = @["-p", MACOS_READ_ONLY_PROFILE, shellExecutable] & args
  let childEnvironment = implSanitizedEnvironment()
  var p: Process
  acquire(processStartLock)
  try:
    p = startProcess(
      executable,
      args = args,
      env = childEnvironment,
      options =
        when defined(posix):
          {poStdErrToStdOut, poUsePath, poDaemon}
        else:
          {poStdErrToStdOut, poUsePath})
    implPreventPipeInheritance(p)
  except OSError as e:
    raise newException(GetError,
      fmt"cannot start read-only command runner '{executable}': {e.msg}")
  except IOError as e:
    raise newException(GetError,
      fmt"cannot start read-only command runner '{executable}': {e.msg}")
  finally:
    release(processStartLock)
  implRegisterProcess(p)

  var didTimeOut = false
  when defined(windows):
    var completed: Atomic[bool]
    var timedOut: Atomic[bool]
    completed.store(false)
    timedOut.store(false)
    var watchdog: Thread[WatchdogContext]
    let usesWatchdog = timeoutSec > 0
    if usesWatchdog:
      let timeoutMs =
        if timeoutSec > high(int) div 1000:
          high(int)
        else:
          timeoutSec * 1000
      createThread(watchdog, implWatchCommand, WatchdogContext(
        process: p,
        completed: addr completed,
        timedOut: addr timedOut,
        timeoutMs: timeoutMs
      ))

  var rawOutput = ""
  var exitCode = -1
  var truncated = false
  var buffer: array[8192, char]
  try:
    # This API supplies no interactive input. Readers of stdin must see EOF
    # instead of waiting for a parent pipe that is never written to.
    p.inputStream.close()
    when defined(posix):
      let outputFd = cint(p.outputHandle)
      let deadline = started + initDuration(seconds = timeoutSec)
      while true:
        var pollTimeout = -1.cint
        if timeoutSec > 0:
          let remaining = deadline - getMonoTime()
          if remaining <= DurationZero:
            didTimeOut = true
            implTerminateProcessTree(p)
            break
          let remainingMs = max(1'i64, remaining.inMilliseconds)
          pollTimeout = cint(min(remainingMs, int64(high(cint))))

        var descriptor = TPollfd(
          fd: outputFd,
          events: POLLIN,
          revents: 0
        )
        let ready = posix.poll(
          addr descriptor, Tnfds(1), pollTimeout)
        if ready == 0:
          didTimeOut = true
          implTerminateProcessTree(p)
          break
        if ready < 0:
          if errno == EINTR:
            continue
          raiseOSError(osLastError())

        let count = int(posix.read(
          outputFd, addr buffer[0], buffer.len))
        if count > 0:
          if implCaptureChunk(
              rawOutput, addr buffer[0], count,
              maxOutputBytes):
            truncated = true
            implTerminateProcessTree(p)
            break
        elif count == 0:
          # Closing stdout is not process completion. Continue enforcing the
          # same deadline instead of applying waitForExit's separate timeout.
          while true:
            exitCode = p.peekExitCode()
            if exitCode != -1:
              break
            if timeoutSec > 0 and getMonoTime() >= deadline:
              didTimeOut = true
              implTerminateProcessTree(p)
              break
            sleep(10)
          break
        elif errno == EINTR or errno == EAGAIN:
          continue
        else:
          raiseOSError(osLastError())
    else:
      let outp = p.outputStream
      while true:
        let count = outp.readData(addr buffer[0], buffer.len)
        if count <= 0:
          exitCode = p.peekExitCode()
          if exitCode != -1:
            break
          continue
        if implCaptureChunk(
            rawOutput, addr buffer[0], count,
            maxOutputBytes):
          if not truncated:
            truncated = true
            implTerminateProcessTree(p)
  finally:
    when defined(windows):
      completed.store(true)
      if usesWatchdog:
        joinThread(watchdog)
      didTimeOut = timedOut.load()
    if exitCode == -1:
      try:
        if not didTimeOut and not truncated:
          implTerminateProcessTree(p)
        exitCode = p.waitForExit(1000)
      except OSError, ValueError:
        exitCode = -1
    implUnregisterProcess(p)
    p.close()

  when defined(windows):
    let output = implNormalizeWindowsOutput(
      rawOutput)
  else:
    let output = rawOutput
  result = ExecResult(
    output: output,
    exitCode:
      if exitCode == -1: 1
      else: exitCode,
    elapsedMs: (getMonoTime() - started).inMilliseconds,
    timedOut: didTimeOut,
    truncated: truncated
  )

## Executes a command with compatibility defaults and captures its output.
##
## This v2-compatible wrapper has no deadline or output cap. New harness code
## uses ``executeCommandBounded`` with explicit budgets.
##
## :param command: Validated command to execute.
## :param shell: Shell executable name or path.
## :returns: An unbounded ExecResult.
## :raises: GetError: If the shell process cannot be started.
##
## .. code-block:: nim
##   runnableExamples:
##     discard
proc executeCommand*(
  command: string,
  shell: string
): ExecResult =
  result = executeCommandBounded(
    command,
    shell,
    timeoutSec = 0,
    maxOutputBytes = 0
  )
